/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;
import Admin.ketnoiqltv;
import QLDNDK.formdangnhap;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.logging.Level;
import javax.swing.JPanel;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author 10052
 */
public class Ql_Admin extends javax.swing.JFrame {
    private ketnoiqltv db;
    /**
     * @throws ClassNotFoundException
     * @throws SQLException
     */
    public Ql_Admin() throws ClassNotFoundException, SQLException {
    initComponents();
    qltailieu.setVisible(false);
    db = new ketnoiqltv();
    popupMenu.add(clickxemthem);

    // ✅ Set CardLayout đúng cách
    menugoc.setLayout(new CardLayout());

    CardLayout card = (CardLayout) menugoc.getLayout();
    card.show(menugoc, "qltailieu");
    menugoc.add(menumain, "menumain");
    menugoc.add(qlnv, "qlnv");
    menugoc.add(qltailieu, "qltailieu");

    }
   
    int width = 315;
    int height = 674;
    void openmenu(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                for(int i = 0 ; i<width;i++){
                    menuchon.setSize(i,height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
    void closemenu(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                for(int i = width ; i>0;i--){
                    menuchon.setSize(i,height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcgoc = new javax.swing.ButtonGroup();
        popupMenu = new javax.swing.JPopupMenu();
        clickxemthem = new javax.swing.JMenuItem();
        menugoc = new javax.swing.JPanel();
        menumain = new javax.swing.JPanel();
        menuchon = new javax.swing.JPanel();
        btnhome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnqltl = new javax.swing.JButton();
        btnqlnv = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btndangsuat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        qlnv = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnaddqlnv = new javax.swing.JButton();
        btnsuaqlnv = new javax.swing.JButton();
        btnxoaqlnv = new javax.swing.JButton();
        btnviewqlnv = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton15 = new javax.swing.JButton();
        btnoutgoc2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbnv = new javax.swing.JTable();
        qltailieu = new JPanel(); // Hoặc gán giá trị từ giao diện thiết kế nếu có
        qltailieu.setVisible(false);
        qltailieu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbTheLoai = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbtrangthai_1_2 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        txtNhaXuatBan = new javax.swing.JTextField();
        txtNamXuatBan = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btnthemqltl = new javax.swing.JButton();
        btnxoaqltl = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btnsuaqltl = new javax.swing.JButton();
        btntimkiemqltl = new javax.swing.JButton();
        txttimkiemqltl = new javax.swing.JTextField();
        timkiemqltl = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        radcosan = new javax.swing.JRadioButton();
        radduocmuon = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtViTri = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        btnoutgoc = new javax.swing.JButton();

        clickxemthem.setText("Xem thêm");
        clickxemthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickxemthemActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 672));

        menugoc.setMinimumSize(new java.awt.Dimension(1240, 680));
        menugoc.setPreferredSize(new java.awt.Dimension(1240, 680));
        menugoc.setLayout(new java.awt.CardLayout());

        menumain.setMaximumSize(new java.awt.Dimension(1240, 32767));
        menumain.setMinimumSize(new java.awt.Dimension(1240, 680));
        menumain.setPreferredSize(new java.awt.Dimension(315, 674));

        menuchon.setBackground(new java.awt.Color(204, 255, 255));
        menuchon.setPreferredSize(new java.awt.Dimension(315, 674));

        btnhome.setBackground(new java.awt.Color(255, 204, 204));
        btnhome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnhome.setText("Trang chủ");
        btnhome.setBorderPainted(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-admin-50.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-quit.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        btnqltl.setBackground(new java.awt.Color(255, 204, 204));
        btnqltl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnqltl.setText("Quản Lý Tài Liệu");
        btnqltl.setBorderPainted(false);
        btnqltl.setFocusable(false);
        btnqltl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqltlActionPerformed(evt);
            }
        });

        btnqlnv.setBackground(new java.awt.Color(255, 204, 204));
        btnqlnv.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnqlnv.setText("Quản lý nhân viên");
        btnqlnv.setAutoscrolls(true);
        btnqlnv.setDefaultCapable(false);
        btnqlnv.setFocusPainted(false);
        btnqlnv.setFocusable(false);
        btnqlnv.setRequestFocusEnabled(false);
        btnqlnv.setRolloverEnabled(false);
        btnqlnv.setVerifyInputWhenFocusTarget(false);
        btnqlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlnvActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Quản lý nhà cung cấp");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 204, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton5.setText("Mượn & Trả sách");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("Báo cáo thống kê");

        btndangsuat.setText("Đăng xuất");
        btndangsuat.setAutoscrolls(true);
        btndangsuat.setDoubleBuffered(true);
        btndangsuat.setFocusCycleRoot(true);
        btndangsuat.setFocusTraversalPolicyProvider(true);
        btndangsuat.setHideActionText(true);
        btndangsuat.setInheritsPopupMenu(true);
        btndangsuat.setVerifyInputWhenFocusTarget(false);
        btndangsuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangsuatActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-logout-50.png"))); // NOI18N

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-home-50 (2).png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-book-48 (1).png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-user-groups-50.png"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-factory-50.png"))); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-exchange-50.png"))); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-statistical-monitoring-50.png"))); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout menuchonLayout = new javax.swing.GroupLayout(menuchon);
        menuchon.setLayout(menuchonLayout);
        menuchonLayout.setHorizontalGroup(
            menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuchonLayout.createSequentialGroup()
                .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuchonLayout.createSequentialGroup()
                        .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(menuchonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)))
                            .addComponent(jLabel21))
                        .addGap(49, 49, 49)
                        .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnqltl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnqlnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(menuchonLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuchonLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(menuchonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btndangsuat, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuchonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuchonLayout.setVerticalGroup(
            menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuchonLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuchonLayout.createSequentialGroup()
                        .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(menuchonLayout.createSequentialGroup()
                                .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(menuchonLayout.createSequentialGroup()
                                        .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(menuchonLayout.createSequentialGroup()
                                                .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(menuchonLayout.createSequentialGroup()
                                                        .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel8))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnqltl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel6))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnqlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel22))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(menuchonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(btndangsuat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-menu-50.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menumainLayout = new javax.swing.GroupLayout(menumain);
        menumain.setLayout(menumainLayout);
        menumainLayout.setHorizontalGroup(
            menumainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menumainLayout.createSequentialGroup()
                .addComponent(menuchon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap(1178, Short.MAX_VALUE))
        );
        menumainLayout.setVerticalGroup(
            menumainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuchon, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
            .addGroup(menumainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menugoc.add(menumain, "menumain");

        qlnv.setMinimumSize(new java.awt.Dimension(1240, 680));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel11.setText("Mã Nhân Viên");

        jLabel26.setText("Họ & Tên");

        jLabel27.setText("Chức vụ");

        jLabel28.setText("SDT");

        jLabel29.setText("Email");

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        btnaddqlnv.setText("Thêm");
        btnaddqlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddqlnvActionPerformed(evt);
            }
        });

        btnsuaqlnv.setText("Sửa");
        btnsuaqlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaqlnvActionPerformed(evt);
            }
        });

        btnxoaqlnv.setText("Xóa");
        btnxoaqlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaqlnvActionPerformed(evt);
            }
        });

        btnviewqlnv.setText("Hiện thị");
        btnviewqlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewqlnvActionPerformed(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-add-50 (1).png"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-repair-50.png"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-delete-50 (1).png"))); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-view-50.png"))); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Nhân Viên", "Họ & Tên", "Chức Vụ", "SDT", "Email" }));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-search-50 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnaddqlnv, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(btnxoaqlnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnviewqlnv, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(btnsuaqlnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddqlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsuaqlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnviewqlnv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnxoaqlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton15))
                .addGap(61, 61, 61))
        );

        btnoutgoc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-left-50.png"))); // NOI18N
        btnoutgoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoutgoc2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnoutgoc2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addComponent(txtHoTen)
                            .addComponent(txtChucVu)
                            .addComponent(txtMaNV)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(txtSDT)))
                .addGap(59, 59, 59))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnoutgoc2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ & Tên", "Chức Vụ", "Số Điện Thoại", "Email"
            }
        ));
        tbnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnvMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbnv);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout qlnvLayout = new javax.swing.GroupLayout(qlnv);
        qlnv.setLayout(qlnvLayout);
        qlnvLayout.setHorizontalGroup(
            qlnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qlnvLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qlnvLayout.setVerticalGroup(
            qlnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(qlnvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menugoc.add(qlnv, "qlnv");

        qltailieu.setDoubleBuffered(false);
        qltailieu.setEnabled(false);
        qltailieu.setFocusable(false);
        qltailieu.setMinimumSize(new java.awt.Dimension(1240, 680));
        qltailieu.setOpaque(false);
        qltailieu.setRequestFocusEnabled(false);
        qltailieu.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Mã tài liệu");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Tên tài liệu");

        cbTheLoai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sách", "Tạp chí", "Báo cáo khoa học", "Luận văn", "Tài liệu tham khảo", "giáo trình", "Ebook", "Truyện" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("Loại tài liệu");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Tác giả");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setText("Nhà sản xuất");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setText("Năm sản xuất");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("ISBN");

        cbtrangthai_1_2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cbtrangthai_1_2.setText("Trạng thái");

        jLabel19.setBackground(new java.awt.Color(153, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 51));
        jLabel19.setText("QUẢN LÝ TÀI LIỆU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-add-50 (1).png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setDefaultCapable(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setRequestFocusEnabled(false);
        jButton7.setRolloverEnabled(false);
        jButton7.setVerifyInputWhenFocusTarget(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnthemqltl.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnthemqltl.setText("Thêm");
        btnthemqltl.setAutoscrolls(true);
        btnthemqltl.setDoubleBuffered(true);
        btnthemqltl.setFocusCycleRoot(true);
        btnthemqltl.setInheritsPopupMenu(true);
        btnthemqltl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemqltlActionPerformed(evt);
            }
        });

        btnxoaqltl.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnxoaqltl.setText("Xóa");
        btnxoaqltl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaqltlActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-delete-50 (1).png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setDefaultCapable(false);
        jButton10.setFocusPainted(false);
        jButton10.setFocusable(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverEnabled(false);
        jButton10.setVerifyInputWhenFocusTarget(false);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-repair-50.png"))); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setDefaultCapable(false);
        jButton11.setFocusPainted(false);
        jButton11.setFocusable(false);

        btnsuaqltl.setText("Sửa");
        btnsuaqltl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaqltlActionPerformed(evt);
            }
        });

        btntimkiemqltl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-search-50 (1).png"))); // NOI18N
        btntimkiemqltl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemqltlActionPerformed(evt);
            }
        });

        timkiemqltl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã tài liệu", "Tên tài liệu", "Loại tài liệu", "Tác giả", "Nhà sản xuất", "Năm sản xuất" }));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel20.setText("Tìm kiếm");

        jButton8.setText("Hiện thị");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-view-50.png"))); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setDefaultCapable(false);
        jButton12.setFocusPainted(false);
        jButton12.setFocusable(false);
        jButton12.setRequestFocusEnabled(false);
        jButton12.setRolloverEnabled(false);
        jButton12.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(timkiemqltl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttimkiemqltl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btntimkiemqltl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnthemqltl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnsuaqltl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnxoaqltl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnthemqltl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoaqltl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsuaqltl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(timkiemqltl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttimkiemqltl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btntimkiemqltl)
                        .addGap(82, 82, 82))))
        );

        lcgoc.add(radcosan);
        radcosan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radcosan.setText("Có sẵn");

        lcgoc.add(radduocmuon);
        radduocmuon.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radduocmuon.setText("Được mượn");

        tb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã TL", "Tên tài liệu", "Tác giả", "Loại tài liệu", "Nhà sản xuất", "Nsx", "ISBN", "SL", "Vị trí", "Trạng thái", "Mã NCC"
            }
        ));
        tb.setMinimumSize(new java.awt.Dimension(120, 78));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb);
        if (tb.getColumnModel().getColumnCount() > 0) {
            tb.getColumnModel().getColumn(0).setMaxWidth(45);
            tb.getColumnModel().getColumn(5).setPreferredWidth(40);
            tb.getColumnModel().getColumn(7).setPreferredWidth(27);
            tb.getColumnModel().getColumn(8).setMaxWidth(60);
            tb.getColumnModel().getColumn(9).setPreferredWidth(40);
            tb.getColumnModel().getColumn(10).setMaxWidth(55);
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Số Lượng");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Vị trí");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel25.setText("Mã NCC");

        btnoutgoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/icons8-left-50.png"))); // NOI18N
        btnoutgoc.setText("jButton9");
        btnoutgoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoutgocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qltailieuLayout = new javax.swing.GroupLayout(qltailieu);
        qltailieu.setLayout(qltailieuLayout);
        qltailieuLayout.setHorizontalGroup(
            qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qltailieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qltailieuLayout.createSequentialGroup()
                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(qltailieuLayout.createSequentialGroup()
                                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(qltailieuLayout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGap(12, 12, 12))
                            .addGroup(qltailieuLayout.createSequentialGroup()
                                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnoutgoc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(qltailieuLayout.createSequentialGroup()
                                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(qltailieuLayout.createSequentialGroup()
                                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaNCC)
                                            .addComponent(txtViTri)))
                                    .addGroup(qltailieuLayout.createSequentialGroup()
                                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radcosan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbtrangthai_1_2)
                                            .addComponent(radduocmuon))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(qltailieuLayout.createSequentialGroup()
                                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(qltailieuLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        qltailieuLayout.setVerticalGroup(
            qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(qltailieuLayout.createSequentialGroup()
                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qltailieuLayout.createSequentialGroup()
                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(qltailieuLayout.createSequentialGroup()
                                .addContainerGap(37, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(qltailieuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnoutgoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(qltailieuLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radduocmuon)))
                            .addGroup(qltailieuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(cbtrangthai_1_2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(cbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radcosan))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(qltailieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        menugoc.add(qltailieu, "qltailieu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menugoc, javax.swing.GroupLayout.PREFERRED_SIZE, 1246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menugoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Auto-generated bởi NetBeans: initComponents()
   
    public void ShowTable() {
    DefaultTableModel model = (DefaultTableModel) tb.getModel();
    model.setRowCount(0);

    try {
        ketnoiqltv pt = new ketnoiqltv();
        ResultSet rs = pt.getData("sach");
        
        // Ensure model has correct columns (add if necessary)
        if (model.getColumnCount() == 0) {
            model.setColumnIdentifiers(new String[]{
                "MaSach", "TenSach", "TacGia", "TheLoai", 
                "NhaXuatBan", "NamXuatBan", "ISBN", 
                "SoLuong", "ViTri", "TrangThai", "MaNhaCungCap"
            });
        }

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("MaSach"),
                rs.getString("TenSach"),
                rs.getString("TacGia"),
                rs.getString("TheLoai"),
                rs.getString("NhaXuatBan"),
                rs.getString("NamXuatBan"),
                rs.getString("ISBN"),
                rs.getString("SoLuong"),
                rs.getString("ViTri"),
                rs.getString("TrangThai"),
                rs.getString("MaNhaCungCap")
            });
        }
    } catch (SQLException | ClassNotFoundException e) {
        e.printStackTrace(); // Proper error logging
    }
}
    public void ShowTBNV() {
    DefaultTableModel model = (DefaultTableModel) tbnv.getModel();
    model.setRowCount(0); // Xoá dữ liệu cũ

    try {
        ketnoiqltv pt = new ketnoiqltv();
        ResultSet rs = pt.getDatanv("");
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("MaNhanVien"),
                rs.getString("HoTen"),
                rs.getString("ChucVu"),
                rs.getString("SoDienThoai"),
                rs.getString("Email")
            });
        }

    } catch (SQLException | ClassNotFoundException e) {
        e.printStackTrace();
    }
}

  
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
    public void Insert() throws ClassNotFoundException, SQLException{
            int maSach = Integer.parseInt(txtMaSach.getText());
            String tenSach = txtTenSach.getText();
            String tacGia = txtTacGia.getText();
            var TheLoai = (String) cbTheLoai.getSelectedItem();
            String nhaXuatBan = txtNhaXuatBan.getText();
            int namXuatBan = Integer.parseInt(txtNamXuatBan.getText());
            String ISBN = txtISBN.getText();
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            String viTri = txtViTri.getText();
            String trangThai = radcosan.isSelected() ? "Có sẵn" : "Đang mượn";
            String maNhaCungCap = txtMaNCC.getText();
        ketnoiqltv kn;
        try{
            kn = new ketnoiqltv();
            kn.insertSach(maSach,tenSach,tacGia,TheLoai,nhaXuatBan,namXuatBan,ISBN,soLuong,viTri,trangThai,maNhaCungCap);
        }catch(SQLException sqlException){
            sqlException.printStackTrace();
        }catch(ClassNotFoundException ex){
            Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    private void btnthemqltlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemqltlActionPerformed
        try {
            Insert();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            ShowTable();
            JOptionPane.showMessageDialog(null, "Đã thêm thành công");
    }//GEN-LAST:event_btnthemqltlActionPerformed

    private void tbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseReleased
        if (evt.isPopupTrigger() && tb.getSelectedRowCount() > 0) {
            int row = tb.rowAtPoint(evt.getPoint());
            tb.setRowSelectionInterval(row, row); // chọn đúng dòng chuột phải

            popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tbMouseReleased
    public void Delete() throws ClassNotFoundException, SQLException {
    int maSach = Integer.parseInt(txtMaSach.getText());
    ketnoiqltv kn;
    try {
        kn = new ketnoiqltv();
        kn.deleteSach(maSach);
    } catch (SQLException sqlException) {
        sqlException.printStackTrace();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    public void DeleteSelectedRow() throws ClassNotFoundException, SQLException {
    int selectedRow = tb.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng cần xóa.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa sách này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    int maSach = Integer.parseInt(tb.getValueAt(selectedRow, 0).toString());

    ketnoiqltv kn;
    try {
        kn = new ketnoiqltv();
        kn.deleteSach(maSach);
    } catch (SQLException sqlException) {
        sqlException.printStackTrace();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    private void clickxemthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickxemthemActionPerformed
        int selectedRow = tb.getSelectedRow();
        if (selectedRow >= 0) {
            // Lấy dữ liệu từ dòng đó
            String tenSach = tb.getValueAt(selectedRow, 1).toString();
            String tacGia = tb.getValueAt(selectedRow, 2).toString();
            String theLoai = tb.getValueAt(selectedRow, 3).toString();
            
            // Hiển thị dialog
            JOptionPane.showMessageDialog(null,
                "Tên sách: " + tenSach + "\nTác giả: " + tacGia + "\nThể loại: " + theLoai,
                "Thông tin chi tiết",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_clickxemthemActionPerformed

    private void btnxoaqltlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaqltlActionPerformed
        try {
        int selectedRow = tb.getSelectedRow();
        if (selectedRow != -1) {
            // Có dòng được chọn trong bảng → dùng DeleteSelectedRow
            DeleteSelectedRow();
            ShowTable();
            JOptionPane.showMessageDialog(null, "Đã xóa thành công (qua bảng)");
        } else if (!txtMaSach.getText().trim().isEmpty()) {
            // Không chọn dòng, nhưng có nhập mã sách → dùng Delete
            Delete();
            ShowTable();
            JOptionPane.showMessageDialog(null, "Đã xóa thành công (qua mã sách)");
        } else {
            // Không chọn dòng và cũng không nhập mã
            JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng hoặc nhập mã sách để xóa.");
        }
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Lỗi khi xóa: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnxoaqltlActionPerformed
    
    public void Update() throws ClassNotFoundException, SQLException {
        int maSach = Integer.parseInt(txtMaSach.getText());
        String tenSach = txtTenSach.getText();
        String tacGia = txtTacGia.getText();
        String theLoai = (String) cbTheLoai.getSelectedItem();
        String nhaXuatBan = txtNhaXuatBan.getText();
        int namXuatBan = Integer.parseInt(txtNamXuatBan.getText());
        String ISBN = txtISBN.getText();
        int soLuong = Integer.parseInt(txtSoLuong.getText());
        String viTri = txtViTri.getText();
        String trangThai = radcosan.isSelected() ? "Có sẵn" : "Đang mượn";
        String maNhaCungCap = txtMaNCC.getText();

        ketnoiqltv kn = new ketnoiqltv();
        kn.updateSach(maSach, tenSach, tacGia, theLoai, nhaXuatBan,
                      namXuatBan, ISBN, soLuong, viTri, trangThai, maNhaCungCap);
    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ShowTable();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnsuaqltlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaqltlActionPerformed
        try {
            Update();
            ShowTable();
            JOptionPane.showMessageDialog(null, "Đã sửa thành công");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsuaqltlActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        int i = tb.getSelectedRow();
        txtMaSach.setText(tb.getValueAt(i, 0).toString());
        txtTenSach.setText(tb.getValueAt(i, 1).toString());
        txtTacGia.setText(tb.getValueAt(i, 2).toString());
        cbTheLoai.setSelectedItem(tb.getValueAt(i, 3).toString());
        txtNhaXuatBan.setText(tb.getValueAt(i, 4).toString());
        txtNamXuatBan.setText(tb.getValueAt(i, 5).toString());
        txtISBN.setText(tb.getValueAt(i, 6).toString());
        txtSoLuong.setText(tb.getValueAt(i, 7).toString());
        txtViTri.setText(tb.getValueAt(i, 8).toString());
        String trangThai = tb.getValueAt(i, 9).toString();
        radcosan.setSelected(trangThai.equals("Có sẵn"));
        txtMaNCC.setText(tb.getValueAt(i, 10).toString());

    }//GEN-LAST:event_tbMouseClicked

    private void btntimkiemqltlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemqltlActionPerformed
    String luaChon = timkiemqltl.getSelectedItem().toString();
    String tuKhoa = txttimkiemqltl.getText().trim();

    if (tuKhoa.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập từ khóa tìm kiếm!");
        return;
    }

    // Map từ ComboBox -> Cột trong SQL
    String truongTim = "";
    switch (luaChon) {
        case "Mã tài liệu":
            truongTim = "MaSach";
            break;
        case "Tên tài liệu":
            truongTim = "TenSach";
            break;
        case "Loại tài liệu":
            truongTim = "TheLoai";
            break;
        case "Tác giả":
            truongTim = "TacGia";
            break;
        case "Nhà sản xuất":
            truongTim = "NhaXuatBan";
            break;
        case "Năm sản xuất":
            truongTim = "NamXuatBan";
            break;
        default:
            JOptionPane.showMessageDialog(null, "Tiêu chí tìm kiếm không hợp lệ!");
            return;
    }

    try {
        ketnoiqltv kn = new ketnoiqltv();
        ResultSet rs = kn.timKiemSach(truongTim, tuKhoa);

        DefaultTableModel model = (DefaultTableModel) tb.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("MaSach"),
                rs.getString("TenSach"),
                rs.getString("TacGia"),
                rs.getString("TheLoai"),
                rs.getString("NhaXuatBan"),
                rs.getInt("NamXuatBan"),
                rs.getString("ISBN"),
                rs.getInt("SoLuong"),
                rs.getString("ViTri"),
                rs.getString("TrangThai"),
                rs.getString("MaNhaCungCap")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Lỗi khi tìm kiếm dữ liệu!");
    }
    }//GEN-LAST:event_btntimkiemqltlActionPerformed

    private void btnoutgocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoutgocActionPerformed
        CardLayout card = (CardLayout) menugoc.getLayout();
        card.show(menugoc, "menumain");

    }//GEN-LAST:event_btnoutgocActionPerformed

    private void btndangsuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangsuatActionPerformed
        formdangnhap formdn = new formdangnhap();
        formdn.setVisible(true);
    }//GEN-LAST:event_btndangsuatActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        closemenu();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnqltlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqltlActionPerformed
        CardLayout card = (CardLayout) menugoc.getLayout();
        card.show(menugoc, "qltailieu");
    }//GEN-LAST:event_btnqltlActionPerformed

    private void btnqlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlnvActionPerformed
        CardLayout card = (CardLayout) menugoc.getLayout();
        card.show(menugoc, "qlnv");
    }//GEN-LAST:event_btnqlnvActionPerformed

    private void btnoutgoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoutgoc2ActionPerformed
        CardLayout card = (CardLayout) menugoc.getLayout();
        card.show(menugoc, "menumain");
    }//GEN-LAST:event_btnoutgoc2ActionPerformed

    private void btnviewqlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewqlnvActionPerformed
        ShowTBNV();
    }//GEN-LAST:event_btnviewqlnvActionPerformed
    public void InsertNhanVien() throws ClassNotFoundException, SQLException {
    int maNV = Integer.parseInt(txtMaNV.getText());
    String hoTen = txtHoTen.getText();
    String chucVu = txtChucVu.getText();
    String sdt = txtSDT.getText();
    String email = txtEmail.getText();

    ketnoiqltv kn;
    try {
        kn = new ketnoiqltv();
        kn.insertNhanVien(maNV, hoTen, chucVu, sdt, email);
    } catch (SQLException sqlException) {
        sqlException.printStackTrace();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    private void btnaddqlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddqlnvActionPerformed
        try {
            InsertNhanVien();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
            ShowTBNV();
            JOptionPane.showMessageDialog(null, "Đã thêm thành công");
    }//GEN-LAST:event_btnaddqlnvActionPerformed
    public void DeleteNhanVien() throws ClassNotFoundException, SQLException {
    int maNV = Integer.parseInt(txtMaNV.getText());
    ketnoiqltv kn;
    try {
        kn = new ketnoiqltv();
        kn.deleteNhanVien(maNV);
    } catch (SQLException sqlException) {
        sqlException.printStackTrace();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    public void DeleteNhanVienFromTable() throws ClassNotFoundException, SQLException {
    int selectedRow = tbnv.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng cần xóa.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa nhân viên này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }
    int maNV = Integer.parseInt(tbnv.getValueAt(selectedRow, 0).toString());
    ketnoiqltv kn;
    try {
        kn = new ketnoiqltv();
        kn.deleteNhanVien(maNV);
    } catch (SQLException sqlException) {
        sqlException.printStackTrace();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    private void btnxoaqlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaqlnvActionPerformed
        try {
        int selectedRow = tbnv.getSelectedRow();
        if (selectedRow != -1) {
            // Có dòng được chọn trong bảng
            DeleteNhanVienFromTable();
            ShowTBNV(); // cập nhật lại bảng
            JOptionPane.showMessageDialog(null, "Đã xóa thành công (qua bảng)");
        } else if (!txtMaNV.getText().trim().isEmpty()) {
            // Có nhập mã nhân viên
            DeleteNhanVien();
            ShowTBNV(); // cập nhật lại bảng
            JOptionPane.showMessageDialog(null, "Đã xóa thành công (qua mã)");
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng hoặc nhập mã nhân viên để xóa.");
        }
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Lỗi khi xóa: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnxoaqlnvActionPerformed
    public void UpdateNhanVien() throws ClassNotFoundException, SQLException {
        int maNV = Integer.parseInt(txtMaNV.getText());
        String hoTen = txtHoTen.getText();
        String chucVu = txtChucVu.getText();
        String sdt = txtSDT.getText();
        String email = txtEmail.getText();

        ketnoiqltv kn;
        try {
            kn = new ketnoiqltv();
            kn.updateNhanVien(maNV, hoTen, chucVu, sdt, email);
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    private void tbnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnvMouseClicked
       int row = tbnv.getSelectedRow();
       if(row >= 0){
           txtMaNV.setText(tbnv.getValueAt(row,0).toString());
           txtHoTen.setText(tbnv.getValueAt(row,1).toString());
           txtChucVu.setText(tbnv.getValueAt(row,2).toString());
           txtSDT.setText(tbnv.getValueAt(row,3).toString());
           txtEmail.setText(tbnv.getValueAt(row,4).toString());
           
       }
    }//GEN-LAST:event_tbnvMouseClicked

    private void btnsuaqlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaqlnvActionPerformed
        try {
        UpdateNhanVien();
        ShowTBNV(); // Cập nhật lại bảng hiển thị
        JOptionPane.showMessageDialog(null, "Cập nhật nhân viên thành công");
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Ql_Admin.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Lỗi khi cập nhật nhân viên: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnsuaqlnvActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        openmenu();
    }//GEN-LAST:event_jButton9ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ql_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ql_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ql_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ql_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new formdangnhap().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddqlnv;
    private javax.swing.JButton btndangsuat;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnoutgoc;
    private javax.swing.JButton btnoutgoc2;
    private javax.swing.JButton btnqlnv;
    private javax.swing.JButton btnqltl;
    private javax.swing.JButton btnsuaqlnv;
    private javax.swing.JButton btnsuaqltl;
    private javax.swing.JButton btnthemqltl;
    private javax.swing.JButton btntimkiemqltl;
    private javax.swing.JButton btnviewqlnv;
    private javax.swing.JButton btnxoaqlnv;
    private javax.swing.JButton btnxoaqltl;
    private javax.swing.JComboBox<String> cbTheLoai;
    private javax.swing.JLabel cbtrangthai_1_2;
    private javax.swing.JMenuItem clickxemthem;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField16;
    private javax.swing.ButtonGroup lcgoc;
    private javax.swing.JPanel menuchon;
    private javax.swing.JPanel menugoc;
    private javax.swing.JPanel menumain;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JPanel qlnv;
    protected javax.swing.JPanel qltailieu;
    private javax.swing.JRadioButton radcosan;
    private javax.swing.JRadioButton radduocmuon;
    private javax.swing.JTable tb;
    private javax.swing.JTable tbnv;
    private javax.swing.JComboBox<String> timkiemqltl;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXuatBan;
    private javax.swing.JTextField txtNhaXuatBan;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtViTri;
    private javax.swing.JTextField txttimkiemqltl;
    // End of variables declaration//GEN-END:variables

}
